### ISSUE TITLE
Internal server error: exception

### ISSUE THREAD

**Issue by julemand101** [simongray/el#8]
Since around 6th of June 2023 I get the following error when trying to fetch the calendar feed:
https://el.simongray.dk/calendar?language=da&currency=DKK&max-price=1.00&region=DK1 
```
Internal server error: exception
```
Also seem like I can't get any new feed when using https://el.simongray.dk since no valid data is received when clicking "Subscribe".

**Comment by simongray** [comment]
Thanks for letting me know. I'll look into it.
